version: '3.1'

services:

  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: imoveis_db
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3310:3306"
    cap_add:
      - SYS_NICE